"""
Django settings for ekisan project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
#import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-bv@*m=fn+=4enh9brpji-7dh*thv#8g4eq506hve(ji_pox=i6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['e-kisan.onrender.com','localhost']


# Application definition

INSTALLED_APPS = [
    'accounts.apps.AccountsConfig',
    'farmer.apps.FarmerConfig',
    'dealer.apps.DealerConfig',
    'myadmin.apps.MyadminConfig',
    #'django.contrib.admin',
    #"admin_notification",
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'channels',
]

NOTIFICATION_MODEL = 'accounts.Users'
#NOTIFICATION_MODELS = ['accounts.User','accounts.Profilepic','accounts.Subscription','accounts.Crops','accounts.Categories','dealer.DealerProfilepic','dealer.Bit','farmer.Product']

ADMIN_SITE_BASE_URL = 'admin/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'farmer.middleware.AuthMiddlewareFarmer',
    'dealer.middleware.AuthMiddlewareDealer',
    'myadmin.middleware.AuthMiddlewareAdmin',
    'farmer.middleware.SubscriptionMiddlewareFarmer',
    'farmer.middleware.PaymentnMiddlewareFarmer',
    'dealer.middleware.SubscriptionMiddlewareDealer',
    'dealer.middleware.PaymentnMiddlewareDealer',
    #'accounts.middleware.AdminNotificationMiddleware',
]



#AUTH_USER_MODEL = 'accounts.Users'  # Specify your custom user model

ROOT_URLCONF = 'ekisan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates' )],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'farmer.context_processors.product_limit_info',
                'dealer.context_processors.bits_context_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'ekisan.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'ekisan',
        'USER': 'postgres',
        'PASSWORD': 'root',
        'HOST': 'localhost',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'ekisan',
#         'USER': 'root',
#         'PASSWORD': 'root',
#         'HOST': 'localhost',
#         'PORT' : '3306'
#     }
# }

# DATABASES = {
#    'default': dj_database_url.parse('postgresql://ekisan_aeo4_user:vzj9WvAzqpk5N6wWjO1HegmZUkBHY6pU@dpg-cs1ctqu8ii6s73d22g9g-a.oregon-postgres.render.com/ekisan_aeo4')
# }



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS=[
    os.path.join(BASE_DIR, 'static')
]
STATIC_ROOT= os.path.join(BASE_DIR, 'assets')


# if not DEBUG:
#     STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
#     STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# if not os.path.exists(MEDIA_ROOT):
#     os.makedirs(MEDIA_ROOT)
    
ASGI_APPLICATION = 'ekisan.routing.application'

RAZORPAY_KEY_ID= 'rzp_test_ZJnfFgi9V8tgCE'
RAZORPAY_KEY_SECRET= 'ItM5DIKdXHVXXUrNusMXTOvN'

GOOGLE_MAPS_API_KEY ='AIzaSyA4ok42pz99BZiplrtRQHs4kzCVQH_fxfQ'
KEY='2GYalXMe31736j6Cz6lRiRHC5N1Yc4zn',
URL='https://www.mapquestapi.com/geocoding/v1/address?key='


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'  # SMTP server host
EMAIL_PORT = 587  # SMTP server port (usually 587 for TLS/STARTTLS)
EMAIL_USE_TLS = True  # Whether to use TLS/STARTTLS for secure connection
EMAIL_HOST_USER = 'talhahamid.syed@gmail.com'  # Your Gmail email address
EMAIL_HOST_PASSWORD = 'talhahamid9229'  # Your Gmail password


TWILIO_ACCOUNT_SID = 'AC0a8f4ab0c471e311d2dab5462426369d'
TWILIO_AUTH_TOKEN = '2caa7d59dc606502ff802fbdaed17d3c'
TWILIO_VERIFY_SERVICE_SID = 'VA28ff9f0b0bb1905913f5fc19e9add96b'
TWILIO_PHONE_NUMBER = '+17627753741'


#FERNET_KEY = b'gklYDfofWuQ6Lt2NelUYKkKiQ0GINs62WuUt-_5S0q0='
